navbar:
  blog_title: 小柴的blog

  navbar:
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill'}
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于我' }
    - { key: 'categories', link: '/categories/', icon: 'iconfont icon-categories-fill', name: '分类'}

force_https: true

post:
  comments:
    enable: true
    type: changyan

changyan:
  appid: cywMKuLHG
  app_secret: 8ab39e796199f25131972cfb48da09c9


index:
  slogan:
    enable: true
    text: 这里是小柴ai的blog